export const returnBondAbi = [
  {
    type: "function",
    name: "createAgreement",
    stateMutability: "nonpayable",
    inputs: [
      { name: "borrower", type: "address" },
      { name: "arbiter", type: "address" },
      { name: "itemName", type: "string" },
      { name: "itemMetadataURI", type: "string" },
      { name: "depositAmount", type: "uint256" },
      { name: "handoverDeadline", type: "uint64" },
      { name: "returnDeadline", type: "uint64" },
      { name: "inspectionPeriod", type: "uint64" },
      { name: "claimResponsePeriod", type: "uint64" },
    ],
    outputs: [{ name: "agreementId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAgreement",
    stateMutability: "view",
    inputs: [{ name: "agreementId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "owner", type: "address" },
          { name: "borrower", type: "address" },
          { name: "arbiter", type: "address" },
          { name: "itemName", type: "string" },
          { name: "itemMetadataURI", type: "string" },
          { name: "depositAmount", type: "uint256" },
          { name: "handoverDeadline", type: "uint64" },
          { name: "returnDeadline", type: "uint64" },
          { name: "inspectionPeriod", type: "uint64" },
          { name: "claimResponsePeriod", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "fundingTimestamp", type: "uint64" },
          { name: "handoverTimestamp", type: "uint64" },
          { name: "returnRequestTimestamp", type: "uint64" },
          { name: "claimCreationTimestamp", type: "uint64" },
          { name: "claimAmount", type: "uint256" },
          { name: "returnProofURI", type: "string" },
          { name: "claimEvidenceURI", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getOwnerAgreementIds",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getBorrowerAgreementIds",
    stateMutability: "view",
    inputs: [{ name: "borrower", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getArbiterAgreementIds",
    stateMutability: "view",
    inputs: [{ name: "arbiter", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "totalAgreementCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "AgreementCreated",
    anonymous: false,
    inputs: [
      { name: "agreementId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "arbiter", type: "address", indexed: false },
      { name: "depositAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "error",
    name: "AgreementNotFound",
    inputs: [{ name: "agreementId", type: "uint256" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "RolesMustBeDistinct", inputs: [] },
  { type: "error", name: "ZeroDeposit", inputs: [] },
  { type: "error", name: "InvalidHandoverDeadline", inputs: [] },
  { type: "error", name: "InvalidReturnDeadline", inputs: [] },
  { type: "error", name: "ZeroInspectionPeriod", inputs: [] },
  { type: "error", name: "ZeroClaimResponsePeriod", inputs: [] },
  { type: "error", name: "EmptyItemName", inputs: [] },
  { type: "error", name: "EmptyMetadataURI", inputs: [] },
] as const;

